version: '3'
services: 
 app:
   container_name: nodejs-container
   restart: always
   build: .
   ports: 
    - '80:3500'
   links: 
    - mongo
 mongo:
  container_name: mongo
  image: mongo
  ports:
    - '27017:27017'